name: mentor-optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda=4.5.12=py36_1000
  - pip=18.1=py36_1000
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - jupyter=1.0.0
  - pip:
    - autopep8==1.5.7
    - flake8==3.9.2
    - python-dotenv==0.19.0
    - statsmodels==0.12.2
    - pytest==6.2.5.
    - pandas==1.1.5
    - scipy==1.5.4
    - pymentor==0.1.1
    - seaborn==0.11.2
    - matplotlib
    - setuptools==58.2.0
    - tqdm==4.62.3
    - wheel==0.37.0
    - -e .
